Update robotframework.yml

diff --git a/.github/workflows/robotframework.yml b/.github/workflows/robotframework.yml
--- a/.github/workflows/robotframework.yml
+++ b/.github/workflows/robotframework.yml
@@ -1,24 +1,47 @@
-name: Robot Framework - Python
+name: Robot Framework CI
+
 on:
   push:
-    branches: [ "integration" ]
+    branches:
+      - integration
   pull_request:
-    branches: [ "integration" ]
-
+    branches:
+      - integration
+      
+      
+      
 permissions:
-  contents: read
-
+    contents: read
 
 jobs:
-  robot_test:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Robot Framework
-        uses: tarathep/robotframework-github-action@v1.0
-        with:
-          image: kietara/robot-framework
-          image_version: 1.0
-          tests_dir: '${{ github.workspace }}/__test__/'
-          reports_dir: '${{ github.workspace }}/__test__/output/'
+    Run-Test:
+      runs-on: ubuntu-20.04
+      steps:
+        - name: Checkout repository
+          uses: actions/checkout@v1
+        - uses: actions/cache@v2
+          id: cache
+          with:
+            path: ~/.cache/pip
+            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
+        - name: Install pip dependencies
+          run: |
+            pip install --upgrade pip
+            pip install -r requirement.txt
+        - name: Run Test
+          run: python -m robot --outputdir ./__test__/output/ ./__test__/. 
+        - name: Run Test and create report
+          run: python -m robot -d reports -x junit-report.xml ./__test__/output/
+        - name: Run Robot Framework tests and generate report
+          run: |
+             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
+        # - name: If Auto Test Pass Rate Not 100%, Job Will Fail
+        #   if: env.ROBOT_RC != '0'
+        #   run: |
+        #     echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
+        #     exit 1
+        - name: Publish test results
+          uses: actions/upload-artifact@v2
+          with:
+            name: robot-test-results
+            path: results
